{% set name = "pytest-recording" %}
{% set version = "0.13.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: dd018421a956ecc45f112c051b1e323b40d029879b1062853df45b05c6098310

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling
  run:
    - attrs
    - pytest >=3.5.0
    - python >=3.7
    - vcrpy >=2.0.1

test:
  imports:
    - pytest_recording
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kiwicom/pytest-recording
  summary: A pytest plugin that allows you recording of network interactions via VCR.py
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/kiwicom/pytest-recording

extra:
  recipe-maintainers:
    - ruben-arts
