{% set name = "pytest-recording" %}
{% set version = "0.13.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1265d679f39263f115968ec01c2a3bfed250170fd1b0d9e288970b2e4a13737a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling
  run:
    - attrs
    - pytest >=3.5.0
    - python >=3.7
    - vcrpy >=2.0.1

test:
  imports:
    - pytest_recording
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kiwicom/pytest-recording
  summary: A pytest plugin that allows you recording of network interactions via VCR.py
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/kiwicom/pytest-recording

extra:
  recipe-maintainers:
    - ruben-arts
