{% set name = "pytest-recording" %}
{% set version = "0.13.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 000c3babbb466681457fd65b723427c1779a0c6c17d9e381c3142a701e124877

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - attrs
    - pytest >=3.5.0
    - python >={{ python_min }}
    - vcrpy >=2.0.1

test:
  imports:
    - pytest_recording
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kiwicom/pytest-recording
  summary: A pytest plugin that allows you recording of network interactions via VCR.py
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/kiwicom/pytest-recording

extra:
  recipe-maintainers:
    - ruben-arts
