{% set name = "pytest-recording" %}
{% set version = "0.12.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-recording-{{ version }}.tar.gz
  sha256: 7c8949c24e5546a699f8fbbff0c5d6896cd09463378ac3d3f1ebb110d2186847

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - attrs
    - pytest >=3.5.0
    - python >=3.5
    - vcrpy >=2.0.1

test:
  imports:
    - pytest_recording
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kiwicom/pytest-recording
  summary: A pytest plugin that allows you recording of network interactions via VCR.py
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/kiwicom/pytest-recording

extra:
  recipe-maintainers:
    - ruben-arts
