# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: pytest-recording
  version: 0.13.4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 568d64b2a85992eec4ae0a419c855d5fd96782c5fb016784d86f18053792768c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
  run:
    - attrs
    - pytest >=3.5.0
    - python >=${{ python_min }}
    - vcrpy >=2.0.1

tests:
  - python:
      imports:
        - pytest_recording
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A pytest plugin that allows you recording of network interactions via VCR.py
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/kiwicom/pytest-recording
  repository: https://github.com/kiwicom/pytest-recording

extra:
  recipe-maintainers:
    - dhirschfeld
    - ruben-arts
